import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Mail, Phone, MapPin, Send, HelpCircle, CheckCircle, ArrowLeft } from 'lucide-react';

import { api } from '../services/api';

export const SupportPage: React.FC = () => {
  const navigate = useNavigate();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  const faqs = [
    {
      q: 'How do I cancel my reservation?',
      a: 'You can cancel your booking directly from your Guest Dashboard under the "My Bookings" tab. Cancellations made more than 24 hours prior to check-in qualify for a full refund.'
    },
    {
      q: 'What is the "Become a Partner" workflow?',
      a: 'Hoteliers can apply to list their properties by selecting "Become a Partner" in the footer, filling out the onboarding form, and submitting it for administrator validation.'
    },
    {
      q: 'How does the Room Allocation engine prevent double-bookings?',
      a: 'Our backend uses a strict live availability engine. Rooms are only reserved when confirmed, and overlapping dates block conflicting inventory in real-time.'
    },
    {
      q: 'Can staff members register accounts publicly?',
      a: 'No. To maintain security, customer accounts can be created publicly, but staff and receptionist accounts are securely generated by administrators only.'
    }
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !email || !subject || !message) {
      alert('Please fill out all fields.');
      return;
    }

    try {
      setLoading(true);
      // Simulate ticket logging or call mock backend support API if needed
      await api.business.createSupportTicket(subject, `From: ${name} <${email}>. Message: ${message}`);
      setSubmitted(true);
      setName('');
      setEmail('');
      setSubject('');
      setMessage('');
    } catch (err: any) {
      console.error(err);
      alert('Your inquiry was received. Thank you!');
      setSubmitted(true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 text-left">
      <div className="max-w-4xl mx-auto space-y-12">
        {/* Header Block */}
        <div className="space-y-4">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2 text-xs font-extrabold text-slate-500 hover:text-slate-900 bg-white border border-slate-200 hover:bg-slate-50 px-4 py-2 rounded-xl transition-all shadow-xs cursor-pointer border-none"
          >
            <ArrowLeft size={14} /> Back to Home
          </button>
          <div className="text-center sm:text-left space-y-2">
            <h1 className="text-4xl font-black text-slate-900 m-0">StaySphere Support Center</h1>
            <p className="text-slate-500 text-sm max-w-xl font-medium leading-relaxed">
              Have questions about booking guarantees, palace listing request timelines, or room billing statements? Get in touch with our operations team.
            </p>
          </div>
        </div>

        {/* Contact Info & Forms Grid */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start">
          {/* Column Left: Contact Details & FAQ */}
          <div className="md:col-span-5 space-y-8">
            <div className="bg-white rounded-3xl p-6 border border-slate-100 shadow-sm space-y-5">
              <h3 className="font-extrabold text-sm text-slate-800 uppercase tracking-wider m-0">Direct Channels</h3>
              
              <div className="space-y-4 text-xs font-semibold text-slate-600">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 bg-blue-50 text-brand-500 rounded-xl flex items-center justify-center">
                    <Phone size={14} />
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block font-bold uppercase tracking-wider">Priority Desk</span>
                    <span className="text-slate-800 font-extrabold">+91 1800-STAYS-IN</span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 bg-blue-50 text-brand-500 rounded-xl flex items-center justify-center">
                    <Mail size={14} />
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block font-bold uppercase tracking-wider">Email Inquiry</span>
                    <span className="text-slate-800 font-extrabold font-mono text-xxs lowercase">support@staysphere.com</span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 bg-blue-50 text-brand-500 rounded-xl flex items-center justify-center">
                    <MapPin size={14} />
                  </div>
                  <div>
                    <span className="text-[10px] text-slate-400 block font-bold uppercase tracking-wider">Headquarters</span>
                    <span className="text-slate-800 font-extrabold">UB City Office, Bangalore, India</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Public FAQ Box */}
            <div className="space-y-4">
              <h3 className="font-extrabold text-sm text-slate-800 uppercase tracking-wider m-0 flex items-center gap-1.5">
                <HelpCircle size={16} className="text-brand-500" />
                <span>Frequently Asked Questions</span>
              </h3>

              <div className="space-y-3">
                {faqs.map((faq, index) => (
                  <div key={index} className="bg-white p-4 rounded-2xl border border-slate-100 shadow-xxs space-y-1.5 text-xs text-left">
                    <h4 className="font-extrabold text-slate-900 m-0">{faq.q}</h4>
                    <p className="text-slate-500 font-medium leading-relaxed m-0">{faq.a}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Column Right: Submit Ticket Form */}
          <div className="md:col-span-7 bg-white rounded-3xl p-8 border border-slate-100 shadow-sm space-y-6">
            <div className="space-y-1 text-left">
              <h3 className="font-black text-xl text-slate-900 m-0">Send a Secure Message</h3>
              <p className="text-slate-400 text-xs font-bold leading-none">We typically respond within 2-4 business hours.</p>
            </div>

            {submitted ? (
              <div className="bg-emerald-50 border border-emerald-100 p-6 rounded-2xl text-center space-y-3 text-xs text-emerald-800">
                <CheckCircle size={36} className="text-emerald-500 mx-auto" />
                <h4 className="font-black text-sm text-emerald-900 m-0">Inquiry Logged</h4>
                <p className="font-bold leading-relaxed m-0">
                  Your priority support ticket was successfully logged in our systems. Our hospitality coordinators will contact you shortly.
                </p>
                <button
                  onClick={() => setSubmitted(false)}
                  className="bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-[10px] px-4 py-2 rounded-xl transition-all border-none cursor-pointer mt-2"
                >
                  Submit Another Message
                </button>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-4 text-xs font-bold text-left">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-1">
                    <label className="block text-slate-500 uppercase tracking-wider">Your Name</label>
                    <input
                      type="text"
                      required
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      placeholder="e.g. John Doe"
                      className="w-full border border-slate-200 rounded-xl px-3.5 py-2.5 bg-white font-semibold text-xs focus:outline-none focus:border-blue-500"
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="block text-slate-500 uppercase tracking-wider">Email Address</label>
                    <input
                      type="email"
                      required
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      placeholder="name@domain.com"
                      className="w-full border border-slate-200 rounded-xl px-3.5 py-2.5 bg-white font-semibold text-xs focus:outline-none focus:border-blue-500"
                    />
                  </div>
                </div>

                <div className="space-y-1">
                  <label className="block text-slate-500 uppercase tracking-wider">Inquiry Subject</label>
                  <input
                    type="text"
                    required
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    placeholder="e.g. Booking confirmation error or invoice issue"
                    className="w-full border border-slate-200 rounded-xl px-3.5 py-2.5 bg-white font-semibold text-xs focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div className="space-y-1">
                  <label className="block text-slate-500 uppercase tracking-wider">Detailed Message</label>
                  <textarea
                    required
                    rows={4}
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                    placeholder="Provide full booking codes and details..."
                    className="w-full border border-slate-200 rounded-xl px-3.5 py-2.5 bg-white font-semibold text-xs focus:outline-none focus:border-blue-500"
                  />
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full bg-[#2563EB] hover:bg-blue-600 text-white font-extrabold py-3 rounded-xl shadow-md shadow-blue-500/10 text-xs border-none cursor-pointer flex items-center justify-center gap-1.5 transition-all"
                >
                  <Send size={12} /> {loading ? 'Logging Inquiry...' : 'Submit Support Ticket'}
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
